# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/86151/Desktop/原神，启动！/BaiduSyncdisk/大三上/并行分布式计算/实验/PSRS_副本

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/86151/Desktop/原神，启动！/BaiduSyncdisk/大三上/并行分布式计算/实验/PSRS_副本

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/86151/Desktop/原神，启动！/BaiduSyncdisk/大三上/并行分布式计算/实验/PSRS_副本/CMakeFiles /mnt/c/Users/86151/Desktop/原神，启动！/BaiduSyncdisk/大三上/并行分布式计算/实验/PSRS_副本/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/86151/Desktop/原神，启动！/BaiduSyncdisk/大三上/并行分布式计算/实验/PSRS_副本/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named psrs

# Build rule for target.
psrs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psrs
.PHONY : psrs

# fast build rule for target.
psrs/fast:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/build
.PHONY : psrs/fast

src/arraygen.o: src/arraygen.cpp.o

.PHONY : src/arraygen.o

# target to build an object file
src/arraygen.cpp.o:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/arraygen.cpp.o
.PHONY : src/arraygen.cpp.o

src/arraygen.i: src/arraygen.cpp.i

.PHONY : src/arraygen.i

# target to preprocess a source file
src/arraygen.cpp.i:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/arraygen.cpp.i
.PHONY : src/arraygen.cpp.i

src/arraygen.s: src/arraygen.cpp.s

.PHONY : src/arraygen.s

# target to generate assembly for a file
src/arraygen.cpp.s:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/arraygen.cpp.s
.PHONY : src/arraygen.cpp.s

src/convert.o: src/convert.cpp.o

.PHONY : src/convert.o

# target to build an object file
src/convert.cpp.o:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/convert.cpp.o
.PHONY : src/convert.cpp.o

src/convert.i: src/convert.cpp.i

.PHONY : src/convert.i

# target to preprocess a source file
src/convert.cpp.i:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/convert.cpp.i
.PHONY : src/convert.cpp.i

src/convert.s: src/convert.cpp.s

.PHONY : src/convert.s

# target to generate assembly for a file
src/convert.cpp.s:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/convert.cpp.s
.PHONY : src/convert.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sort.o: src/sort.cpp.o

.PHONY : src/sort.o

# target to build an object file
src/sort.cpp.o:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/sort.cpp.o
.PHONY : src/sort.cpp.o

src/sort.i: src/sort.cpp.i

.PHONY : src/sort.i

# target to preprocess a source file
src/sort.cpp.i:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/sort.cpp.i
.PHONY : src/sort.cpp.i

src/sort.s: src/sort.cpp.s

.PHONY : src/sort.s

# target to generate assembly for a file
src/sort.cpp.s:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/sort.cpp.s
.PHONY : src/sort.cpp.s

src/time.o: src/time.cpp.o

.PHONY : src/time.o

# target to build an object file
src/time.cpp.o:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/time.cpp.o
.PHONY : src/time.cpp.o

src/time.i: src/time.cpp.i

.PHONY : src/time.i

# target to preprocess a source file
src/time.cpp.i:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/time.cpp.i
.PHONY : src/time.cpp.i

src/time.s: src/time.cpp.s

.PHONY : src/time.s

# target to generate assembly for a file
src/time.cpp.s:
	$(MAKE) -f CMakeFiles/psrs.dir/build.make CMakeFiles/psrs.dir/src/time.cpp.s
.PHONY : src/time.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... psrs"
	@echo "... src/arraygen.o"
	@echo "... src/arraygen.i"
	@echo "... src/arraygen.s"
	@echo "... src/convert.o"
	@echo "... src/convert.i"
	@echo "... src/convert.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sort.o"
	@echo "... src/sort.i"
	@echo "... src/sort.s"
	@echo "... src/time.o"
	@echo "... src/time.i"
	@echo "... src/time.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

